
export const REGISTER_USER_START =   'REGISTER_USER_START';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL =    'REGISTER_USER_FAIL';

export const LOGIN_USER_START =    'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS =  'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL =     'LOGIN_USER_FAIL';



export const GET_ALL_POSTS_START =   'GET_ALL_POSTS_START';
export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS';
export const GET_ALL_POSTS_FAIL =    'GET_ALL_POSTS_FAIL';

export const DELETE_POST_START =   'DELETE_POST_START';
export const DELETE_POST_SUCCESS = 'DELTE_POST_SUCCESS';
export const DELETE_POST_FAIL = '   DELETE_POST_FAIL';

export const GET_MY_POSTS_START =   'GET_MY_POSTS_START';
export const GET_MY_POSTS_SUCCESS = 'GET_MY_POSTS_SUCCESS';
export const GET_MY_POSTS_FAIL =    'GET_MY_POSTS_FAIL';

export const ADD_POST_START =   'ADD_POST_START';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_FAIL =    'ADD_POST_FAIL'