
export const REGISTER_USER_START =   'REGISTER_USER_START';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL =    'REGISTER_USER_FAIL';

export const LOGIN_USER_START =    'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS =  'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL =     'LOGIN_USER_FAIL';

export const LOGOUT_USER = 'LOGOUT_USER';


export const GET_ALL_POSTS_START =   'GET_ALL_POSTS_START';
export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS';
export const GET_ALL_POSTS_FAIL =    'GET_ALL_POSTS_FAIL';

export const DELETE_POST_START =   'DELETE_POST_START';
export const DELETE_POST_SUCCESS = 'DELTE_POST_SUCCESS';
export const DELETE_POST_FAIL =    'DELETE_POST_FAIL';

export const GET_MY_POSTS_START =   'GET_MY_POSTS_START';
export const GET_MY_POSTS_SUCCESS = 'GET_MY_POSTS_SUCCESS';
export const GET_MY_POSTS_FAIL =    'GET_MY_POSTS_FAIL';

export const REMOVE_ALL_POSTS = 'REMOVE_ALL_POSTS'

export const ADD_POST_START =   'ADD_POST_START';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_FAIL =    'ADD_POST_FAIL';

export const ADD_FOLLOWER_START= 'ADD_FOLLOWER_START';
export const ADD_FOLLOWER_SUCCESS = 'ADD_FOLLOWER_SUCCESS';
export const ADD_FOLLOWER_FAIL = 'ADD_FOLLOWER_FAIL';

export const GET_MY_FOLLOWERS_START = 'GET_MY_FOLLOWERS_START';
export const GET_MY_FOLLOWERS_SUCCESS = 'GET_MY_FOLLOWERS_SUCCESS';
export const GET_MY_FOLLOWERS_FAIL = 'GET_MY_FOLLOWERS_FAIL';

export const GET_WHO_I_FOLLOW_START = 'GET_WHO_I_FOLLOW_START';
export const GET_WHO_I_FOLLOW_SUCCESS = 'GET_WHO_I_FOLLOW_SUCCESS';
export const GET_WHO_I_FOLLOW_FAIL = 'GET_WHO_I_FOLLOW_FAIL';